---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['~/cloudbox/accounts.yml', '~/cloudbox/defaults/accounts.yml.default']
    - ['~/cloudbox/settings.yml', '~/cloudbox/defaults/settings.yml.default']
    - ['~/cloudbox/adv_settings.yml', '~/cloudbox/defaults/adv_settings.yml.default']
  roles:
    - { role: pre_tasks }
    - { role: calibre, tags: ['calibre'] }
    - { role: cloudcmd, tags: ['cloudcmd'] }
    - { role: ubooquity, tags: ['ubooquity'] }
    - { role: wallabag, tags: ['wallabag'] }
    - { role: xbackbone, tags: ['xbackbone'] }
