---
calibre:
  domain:
  subdomain:
cloudcmd:
  domain:
  subdomain:
ubooquity:
  domain:
  subdomain:
wallabag:
  domain:
  subdomain:
xbackbone:
  domain:
  subdomain:
  maxupload: 2G
  storage: /mnt/local/xbackbone
