---
role_app_name: "grafana"
role_docker_image: "grafana/grafana"

role_subdomain: "{{ role_app_name }}"
role_opt_path: "/opt/{{ role_app_name }}/"

role_domain:
role_directories:   
  - "{{ role_opt_path }}"
  - "{{ role_opt_path }}config"
  

role_custom_docker_env:
  - VIRTUAL_PORT: "3000"
  - GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-worldmap-panel"
  
role_docker_volumes:
  - /etc/localtime:/etc/localtime:ro
  - "{{ role_opt_path }}config:/var/lib/influxdb"

role_docker_ports:
  - "127.0.0.1:3000:3000"