---
role_app_name: "coder"
role_docker_image: "codercom/code-server"

role_subdomain: "{{ role_app_name }}"
role_opt_path: "/opt/{{ role_app_name }}/"

role_domain:
role_directories:   
  - "{{ role_opt_path }}"

role_custom_docker_env:
  - VIRTUAL_PORT: "8080"
  - PASSWORD: "{{ user.pass }}"
  
role_docker_volumes:
  - "/home/{{ user.name }}/workspaces:/home/coder/project"
  - "/mnt:/mnt"
  - "/opt:/host_opt"
  - "/home/{{ user.name }}:/home/coder/host"

role_published_ports:
  - "127.0.0.1:8143:8080"
 