---
role_app_name: "ubooquity"
role_docker_image: "linuxserver/ubooquity"

role_subdomain: "{{ role_app_name }}"
role_opt_path: "/opt/{{ role_app_name }}/"

role_domain:
role_directories:   
  - "{{ role_opt_path }}config"
  - "{{ role_opt_path }}files"
  - "{{ media_path_books }}"
  - "{{ media_path_comics }}"
role_custom_docker_env:
  - VIRTUAL_PORT: "2203"
role_docker_volumes:
  - "/opt/ubooquity/config:/config"
  - "/opt/ubooquity/files:/files"
  - "/mnt/unionfs/Media/Comics:/comics"
  - "/mnt/unionfs/Media/Books:/books"