---
role_app_name: "lazylibrarian"
role_docker_image: "thraxis/lazylibrarian-calibre"

role_subdomain: "{{ role_app_name }}"
role_opt_path: "/opt/{{ role_app_name }}/"

role_domain:
role_directories:   
  - "{{ role_opt_path }}"

role_custom_docker_env:
  - VIRTUAL_PORT: "5299"
role_docker_volumes:
  - "{{ role_opt_path }}:/config"
  - "/mnt:/mnt"

role_docker_ports:
  - "127.0.0.1:5299:5299"