---
role_app_name: "varken"
role_docker_image: "boerderij/varken"

role_subdomain: "{{ role_app_name }}"
role_opt_path: "/opt/{{ role_app_name }}/"

role_domain:
role_directories:   
  - "{{ role_opt_path }}"
  - "{{ role_opt_path }}config"
  
common_subdomain: "{{ role_subdomain|default(role_app_name,true) }}"
common_fulldomain: "{{ common_subdomain }}.{{ role_domain | default(user.domain,true) }}"

role_custom_docker_env:
  - VIRTUAL_PORT: "8080"
  
role_docker_volumes:
  - /etc/localtime:/etc/localtime:ro
  - "{{ role_opt_path }}config:/config"

role_docker_ports:
  - "127.0.0.1:6601:8080"